### PR TITLE
Use .Net 8.0 instead of .Net 7.0

### PR DESCRIPTION
**Pull request by zhuxb711**
1. Update some third-party components
2. Remove netcoreapp2.0 from test project due to security vulnerability
3. Mark library as Trimmable
4. Support .Net 8.0 and drop support for .Net 7.0

### CODE REVIEW

**Comment by zhuxb711** [comment]
@noamyogev84 Hello there, would you please help review and release a new version to Nuget? Thanks~

**Review by noamyogev84 — APPROVED** [review]
Great stuff @zhuxb711 !! 👏 👏 
Thanks!

**Comment by zhuxb711** [comment]
@noamyogev84 Would you please help merge this PR since I do not have permission, thanks~

**Comment by noamyogev84** [comment]
it'll take me some time to release a Nuget. i'm pretty busy these days.
I'll update.

**Pull request merged**
